### ISSUE TITLE
Link to the tutorial - Climate Impact Rating system doesn't work.

### ISSUE THREAD

**Issue by easynut** [Call-for-Code/Solution-Starter-Kit-Energy-2020#32]
the link to the tutorial doesn't work.

https://developer.ibm.com/tutorials/provision-a-couchdb-instance-using-cloudant-cfc-starter-kit-2/

![image](https://user-images.githubusercontent.com/19815045/78357321-d6cce680-75e3-11ea-960a-6156d6428336.png)

**Comment by derekteay** [comment]
Fixed! Thanks for reporting.
